### ISSUE TITLE
有几个问题请教下

### ISSUE THREAD

**Issue by Jimmuy** [MeandNi/flutter_navigator_v2#1]
1.对于RouterDelegate的实现类，是不是在一个项目中会存在多个？需要针对不同的模块来定制不同的delegate.
2.界面传参有没有什么好办法，目前只看到了通过解析url来进行参数解析
3.setNewRoutePath有什么作用吗？我看就开始进入界面 的时候调用了一次，后面就没有在调用这个方法了，去掉之后对于页面逻辑也没有什么影响
多谢，再研究研究，目前看的有点懵

**Comment by MeandNi** [comment]
1、是的，可以存在多个 RouterDelegate。
2、传参可以定义自己的 model 类供上层调用，这一块需要根据需求定制，可以参考我的水果列表示例，还有我的文章 https://juejin.im/post/6893319571881590797/
3、setNewRoutePath 可以用来做路由状态的更新，比如从系统通知进来重新冷启对路由栈更新

**Comment by Jimmuy** [comment]
> 1、是的，可以存在多个 RouterDelegate。
> 2、传参可以定义自己的 model 类供上层调用，这一块需要根据需求定制，可以参考我的水果列表示例，还有我的文章 https://juejin.im/post/6893319571881590797/
> 3、setNewRoutePath 可以用来做路由状态的更新，比如从系统通知进来重新冷启对路由栈更新

多谢！买了你的书支持一下，加油哈哈哈
